package wily.bedrock4j.util;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.Level;
import wily.factoryapi.FactoryAPI;
import wily.bedrock4j.client.LegacyTipManager;

public class LegacyComponents {
    public static final Component RESOURCE_ALBUMS = Component.translatable("bedrock4j.menu.albums.resource");
    public static final Component ALBUM_OPTIONS = Component.translatable("bedrock4j.menu.album_options");
    public static final Component GLOBAL_RESOURCE_PACKS = Component.translatable("bedrock4j.menu.global_packs.resource");
    public static final Component SELECT = Component.translatable("mco.template.button.select");
    public static final Component USE = Component.translatable("key.use");
    public static final Component ACTION = Component.translatable("key.attack");
    public static final Component ADD = Component.translatable("bedrock4j.action.add");
    public static final Component ADD_PAGE = Component.translatable("bedrock4j.action.add_page");
    public static final Component ATTACH = Component.translatable("bedrock4j.action.attach");
    public static final Component ALL_RECIPES = Component.translatable("bedrock4j.action.all_recipes");
    public static final Component BLOCK = Component.translatable("bedrock4j.action.block");
    public static final Component BOOST = Component.translatable("bedrock4j.action.boost");
    public static final Component BRUSH = Component.translatable("bedrock4j.action.brush");
    public static final Component CANCEL = Component.translatable("bedrock4j.action.cancel");
    public static final Component CARVE = Component.translatable("bedrock4j.action.carve");
    public static final Component CHANGE_FILTER = Component.translatable("bedrock4j.action.change_filter");
    public static final Component CHANGE_PITCH = Component.translatable("bedrock4j.action.change_pitch");
    public static final Component CHARGE = Component.translatable("bedrock4j.action.charge");
    public static final Component CLEAR = Component.translatable("bedrock4j.action.clear");
    public static final Component CLEAR_QUICK_SELECT = Component.translatable("bedrock4j.action.clear_quick_select");
    public static final Component COLLECT = Component.translatable("bedrock4j.action.collect");
    public static final Component COOK = Component.translatable("bedrock4j.action.cook");
    public static final Component CREATE = Component.translatable("bedrock4j.action.create");
    public static final Component DIG_PATH = Component.translatable("bedrock4j.action.dig_path");
    public static final Component DISMOUNT = Component.translatable("bedrock4j.action.dismount");
    public static final Component DISTRIBUTE = Component.translatable("bedrock4j.action.distribute");
    public static final Component DRAW = Component.translatable("bedrock4j.action.draw");
    public static final Component DRINK = Component.translatable("bedrock4j.action.drink");
    public static final Component DROP = Component.translatable("bedrock4j.action.drop");
    public static final Component DROP_ALL = Component.translatable("bedrock4j.action.drop_all");
    public static final Component DROP_ONE = Component.translatable("bedrock4j.action.drop_one");
    public static final Component DYE = Component.translatable("bedrock4j.action.dye");
    public static final Component EAT = Component.translatable("bedrock4j.action.eat");
    public static final Component EJECT = Component.translatable("bedrock4j.action.eject");
    public static final Component EMPTY = Component.translatable("bedrock4j.action.empty");
    public static final Component EQUIP = Component.translatable("bedrock4j.action.equip");
    public static final Component EXIT = Component.translatable("bedrock4j.action.exit");
    public static final Component EXIT_SEARCH_MODE = Component.translatable("bedrock4j.action.exit_search_mode");
    public static final Component FEED = Component.translatable("bedrock4j.action.feed");
    public static final Component FILL = Component.translatable("bedrock4j.action.fill");
    public static final Component FOLLOW_ME = Component.translatable("bedrock4j.action.follow_me");
    public static final Component GROUP = Component.translatable("bedrock4j.action.group");
    public static final Component GROW = Component.translatable("bedrock4j.action.grow");
    public static final Component HEAL = Component.translatable("bedrock4j.action.heal");
    public static final Component HIT = Component.translatable("bedrock4j.action.hit");
    public static final Component IGNITE = Component.translatable("bedrock4j.action.ignite");
    public static final Component INFO = Component.translatable("bedrock4j.action.info");
    public static final Component LAUNCH = Component.translatable("bedrock4j.action.launch");
    public static final Component LEASH = Component.translatable("bedrock4j.action.leash");
    public static final Component LOCK = Component.translatable("bedrock4j.action.lock");
    public static final Component LOVE_MODE = Component.translatable("bedrock4j.action.love_mode");
    public static final Component MINE = Component.translatable("bedrock4j.action.mine");
    public static final Component MOUNT = Component.translatable("bedrock4j.action.mount");
    public static final Component MOVE_FUEL = Component.translatable("bedrock4j.action.move_fuel");
    public static final Component MOVE_INGREDIENT = Component.translatable("bedrock4j.action.move_ingredient");
    public static final Component MOVE_KEYBOARD = Component.translatable("bedrock4j.action.move_keyboard");
    public static final Component MOVE_LAYER = Component.translatable("bedrock4j.action.move_layer");
    public static final Component MOVE_UP_DOWN = Component.translatable("bedrock4j.action.move_up_down");
    public static final Component NAME = Component.translatable("bedrock4j.action.name");
    public static final Component NEXT_PAGE = Component.translatable("bedrock4j.action.next_page");
    public static final Component OPEN = Component.translatable("bedrock4j.action.open");
    public static final Component OPEN_DIRECTORY = Component.translatable("bedrock4j.action.open_directory");
    public static final Component PAGE = Component.translatable("bedrock4j.action.page");
    public static final Component PAGE_DOWN = Component.translatable("bedrock4j.action.page_down");
    public static final Component PAGE_UP = Component.translatable("bedrock4j.action.page_up");
    public static final Component PEEL_BARK = Component.translatable("bedrock4j.action.peel_bark");
    public static final Component PICK_ENTITY = Component.translatable("bedrock4j.action.pick_entity");
    public static final Component PICK_UP = Component.translatable("bedrock4j.action.pick_up");
    public static final Component PLACE = Component.translatable("bedrock4j.action.place");
    public static final Component PLACE_ONE = Component.translatable("bedrock4j.action.place_one");
    public static final Component PLANT = Component.translatable("bedrock4j.action.plant");
    public static final Component PLAY = Component.translatable("bedrock4j.action.play");
    public static final Component PRESETS = Component.translatable("bedrock4j.action.presets");
    public static final Component PREVIOUS_PAGE = Component.translatable("bedrock4j.action.previous_page");
    public static final Component QUICK_MOVE = Component.translatable("bedrock4j.action.quick_move");
    public static final Component RELEASE = Component.translatable("bedrock4j.action.release");
    public static final Component REMOVE = Component.translatable("bedrock4j.action.remove");
    public static final Component REPAIR = Component.translatable("bedrock4j.action.repair");
    public static final Component RIDE = Component.translatable("bedrock4j.action.ride");
    public static final Component SADDLE = Component.translatable("bedrock4j.action.saddle");
    public static final Component SAIL = Component.translatable("bedrock4j.action.sail");
    public static final Component SEARCH_MODE = Component.translatable("bedrock4j.action.search_mode");
    public static final Component SELECT_TAB = Component.translatable("bedrock4j.action.select_tab");
    public static final Component SHEAR = Component.translatable("bedrock4j.action.shear");
    public static final Component SEND_COMMAND = Component.translatable("bedrock4j.action.send_command");
    public static final Component SEND_MESSAGE = Component.translatable("bedrock4j.action.send_message");
    public static final Component SHOW_ADVANCED_OPTIONS = Component.translatable("bedrock4j.action.show_advanced_options");
    public static final Component SHOW_CHAT = Component.translatable("bedrock4j.action.show_chat");
    public static final Component SHOW_CRAFTABLE_RECIPES = Component.translatable("bedrock4j.action.show_craftable_recipes");
    public static final Component SHOW_DESCRIPTION = Component.translatable("bedrock4j.action.show_description");
    public static final Component SHOW_KEYBOARD = Component.translatable("bedrock4j.action.show_keyboard");
    public static final Component SHOW_RESOURCE_PACKS = Component.translatable("bedrock4j.action.show_resource_packs");
    public static final Component SIT = Component.translatable("bedrock4j.action.sit");
    public static final Component SLEEP = Component.translatable("bedrock4j.action.sleep");
    public static final Component SWAP = Component.translatable("bedrock4j.action.swap");
    public static final Component SWIM_UP = Component.translatable("bedrock4j.action.swim_up");
    public static final Component TAKE = Component.translatable("bedrock4j.action.take");
    public static final Component TAKE_ALL = Component.translatable("bedrock4j.action.take_all");
    public static final Component TAKE_HALF = Component.translatable("bedrock4j.action.take_half");
    public static final Component TAME = Component.translatable("bedrock4j.action.tame");
    public static final Component THROW = Component.translatable("bedrock4j.action.throw");
    public static final Component TILL = Component.translatable("bedrock4j.action.till");
    public static final Component TRADE = Component.translatable("bedrock4j.action.trade");
    public static final Component TYPE = Component.translatable("bedrock4j.action.type");
    public static final Component UNLOCK = Component.translatable("bedrock4j.action.unlock");
    public static final Component USE_SUGGESTION = Component.translatable("bedrock4j.action.use_suggestion");
    public static final Component WAKE_UP = Component.translatable("bedrock4j.action.wake_up");
    public static final Component WHATS_THIS = Component.translatable("bedrock4j.action.whats_this");
    public static final Component ZOOM = Component.translatable("bedrock4j.action.zoom");
    public static final Component LAYER_OPTIONS = Component.translatable("bedrock4j.menu.create_flat_world.layer_options");
    public static final Component LAYER_MESSAGE = Component.translatable("bedrock4j.menu.create_flat_world.layer_message");
    public static final Component AUTOSAVE_MESSAGE = Component.translatable("bedrock4j.menu.autoSave_message");
    public static final Component SAVE_OPTIONS = Component.translatable("bedrock4j.menu.save_options");
    public static final Component SAVE_OPTIONS_MESSAGE = Component.translatable("bedrock4j.menu.save_options_message");
    public static final Component SAVE_GAME = Component.translatable("bedrock4j.menu.save");
    public static final Component SAVE_GAME_MESSAGE = Component.translatable("bedrock4j.menu.save_message");
    public static final Component ENABLE_AUTO_SAVE = Component.translatable("bedrock4j.menu.enable_autosave");
    public static final Component ENABLE_AUTO_SAVE_MESSAGE = Component.translatable("bedrock4j.menu.enable_autosave_message");
    public static final Component DISABLE_AUTO_SAVE = Component.translatable("bedrock4j.menu.disable_autosave");
    public static final Component DISABLE_AUTO_SAVE_MESSAGE = Component.translatable("bedrock4j.menu.disable_autosave_message");
    public static final Component SERVER_OPTIONS = Component.translatable("bedrock4j.menu.server_options");
    public static final Component SERVER_OPTIONS_MESSAGE = Component.translatable("bedrock4j.menu.server_options_message");
    public static final Component MISSING_WORLD_TEMPLATE = Component.translatable("bedrock4j.menu.missing_world_template");
    public static final Component GAME_OPTIONS = Component.translatable("bedrock4j.menu.game_options");
    public static final Component WORLD_OPTIONS = Component.translatable("createWorld.tab.world.title");
    public static final Component INGREDIENTS = Component.translatable("bedrock4j.container.ingredients");
    public static final Component COLOR_TAB = Component.translatable("bedrock4j.container.tab.color");
    public static final Component SHAPE_TAB = Component.translatable("bedrock4j.container.tab.shape");
    public static final Component EFFECT_TAB = Component.translatable("bedrock4j.container.tab.effect");
    public static final Component SELECT_STAR_TAB = Component.translatable("bedrock4j.container.tab.select_star");
    public static final Component ADD_FADE_TAB = Component.translatable("bedrock4j.container.tab.add_fade");
    public static final Component ADD_POWER_TAB = Component.translatable("bedrock4j.container.tab.add_power");
    public static final Component SELECT_SHIELD = Component.translatable("bedrock4j.container.tab.select_shield");
    public static final Component COPY_BANNER = Component.translatable("bedrock4j.container.tab.copy_banner");
    public static final Component ADD_SHERD = Component.translatable("bedrock4j.container.tab.add_pottery_sherd");
    public static final Component SELECT_BANNER_TAB = Component.translatable("bedrock4j.container.tab.select_banner");
    public static final Component CREATE_BANNER_TAB = Component.translatable("bedrock4j.container.tab.create_banner");
    public static final Component TAKE_BOOK = Component.translatable("lectern.take_book");
    public static final Component PREVIEW = Component.translatable("bedrock4j.container.preview");
    public static final Component DECORATIONS = Component.translatable("bedrock4j.createWorld.customize.superFlat.decorations");
    public static final Component LAVA_LAKES = Component.translatable("bedrock4j.createWorld.customize.superFlat.lavaLakes");
    public static final Component RESPAWNING = Component.translatable("bedrock4j.menu.respawning");
    public static final Component OPEN_LINK_TITLE = Component.translatable("bedrock4j.menu.open_link_title");
    public static final Component OPEN_LINK_MESSAGE = Component.translatable("bedrock4j.menu.open_link_message");
    public static final Component RESET_KNOWN_ENTITIES_TITLE = Component.translatable("bedrock4j.menu.reset_known_entities");
    public static final Component RESET_KNOWN_ENTITIES_MESSAGE = Component.translatable("bedrock4j.menu.reset_known_entities_message");
    public static final Component RESET_KNOWN_BLOCKS_TITLE = Component.translatable("bedrock4j.menu.reset_known_blocks");
    public static final Component RESET_KNOWN_BLOCKS_MESSAGE = Component.translatable("bedrock4j.menu.reset_known_blocks_message");
    public static final Component SELECTION = Component.literal("...");
    public static final Component NONE = Component.translatable("bedrock4j.options.none");
    public static final Component NEEDS_RESTART = Component.translatable("bedrock4j.options.needs_restart");
    public static final Component MAY_BE_A_CHEAT = Component.translatable("bedrock4j.options.may_be_a_cheat");
    public static final Component ALPHABETICAL = Component.translatable("bedrock4j.menu.sorting.alphabetical");
    public static final Component ALL = Component.translatable("bedrock4j.menu.settings.all");
    public static final Component ACCEPT = Component.translatable("bedrock4j.menu.accept");
    public static final Component STRUCTURES = Component.translatable("bedrock4j.container.tab.structures");
    public static final Component MECHANISMS = Component.translatable("bedrock4j.container.tab.mechanisms");
    public static final Component TOOLS_AND_ARMOUR = Component.translatable("bedrock4j.container.tab.tools_and_armour");
    public static final Component MISC = Component.translatable("bedrock4j.container.tab.misc");
    public static final Component SEARCH_ITEMS = Component.translatable("itemGroup.search");
    public static final Component CONFLICTING_BUTTONS = Component.translatable("bedrock4j.options.controllerMappingConflicting");
    public static final Component CONFLICTING_KEYS = Component.translatable("bedrock4j.options.keyMappingConflicting");
    public static final Component PEACEFUL_SPAWN_TIP = Component.translatable("item.minecraft.spawn_egg.peaceful.tip");

    public static Component optionName(String key){
        return Component.translatable("bedrock4j.options."+key);
    }

    public static Component getDimensionName(ResourceKey<Level> dimension){
        String s = dimension.location().toLanguageKey("dimension");
        return Component.translatable(!FactoryAPI.isClient() || LegacyTipManager.hasTip(s) ? s : "dimension.minecraft");
    }

    public static Component getEnteredDimensionMessage(Component name, ResourceKey<Level> dimension){
        return Component.translatable("bedrock4j.chat.entered_dimension", name, getDimensionName(dimension));
    }

    public static Component getLeftDimensionMessage(Component name, ResourceKey<Level> dimension){
        return Component.translatable("bedrock4j.chat.left_dimension", name, getDimensionName(dimension));
    }
}
